[project]
name = 'S-pay'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 2
epoch = 'latest'
[contracts.s-pay]
path = 'contracts/s-pay.clar'
clarity_version = 2
epoch = 'latest'
[contracts.s-pay-token]
path = 'contracts/s-pay-token.clar'
clarity_version = 2
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
